name: Inspect repo

on:
  workflow_dispatch:

jobs:
  inspect:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List bin folder
        run: ls bin -Recurse

      - name: Show gdextension file
        run: Get-Content bin\*.gdextension
